# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NetsuiteCli < Formula
  desc "CLI for the NetSuite API"
  homepage "https://github.com/paulmeller/netsuite-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.2.0/netsuite-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "928b0a2c20dd99cbf4ce843b0a10c71ed61d3b25333942a0822de6ca29bff2de"

      define_method(:install) do
        bin.install "netsuite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.2.0/netsuite-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "df46dc0fec9156f751acad9d8019a1217f73ae7da94ccfdefaef788f4f5e39dc"

      define_method(:install) do
        bin.install "netsuite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.2.0/netsuite-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "c0e3dc29b2628341abad1d3b6c56a3b35f45b3cef7f999b45212ea8ad88919be"
      define_method(:install) do
        bin.install "netsuite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.2.0/netsuite-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "ba3ec5ec1bbf8f6673cd6d01d1dad8ec4d3a6ebefb3f7ae950505916f1b5bdf3"
      define_method(:install) do
        bin.install "netsuite"
      end
    end
  end

  test do
    assert_match "NetSuite", shell_output("#{bin}/netsuite --help")
  end
end
