# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NetsuiteCli < Formula
  desc "CLI for the NetSuite API"
  homepage "https://github.com/paulmeller/netsuite-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.1.0/netsuite-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "55f708891db524af2accebf9a14e3e4d433f5a5442d04153ec27d6bd25bfe8f9"

      define_method(:install) do
        bin.install "netsuite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.1.0/netsuite-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "39ee0ec936ea37f45187b0664a0f4a6d18be30078f7f1ad303ccdd1627d52298"

      define_method(:install) do
        bin.install "netsuite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.1.0/netsuite-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "0e726fc7ce6b61d377af86f718e3b1d8fe97d8985f9663f9d546c092436a658c"
      define_method(:install) do
        bin.install "netsuite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/netsuite-cli/releases/download/v0.1.0/netsuite-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "09ef925f057e05f063517ecb161780db2b3dab27bb419d79bb50abc1162debf1"
      define_method(:install) do
        bin.install "netsuite"
      end
    end
  end

  test do
    assert_match "NetSuite", shell_output("#{bin}/netsuite --help")
  end
end
