# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XeroCli < Formula
  desc "CLI for the Xero accounting API"
  homepage "https://github.com/paulmeller/xero-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.0/xero-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "7e00479c61011fed94a9cb4282320d1fe4495488db693ee6f7a8b58b85d208cb"

      define_method(:install) do
        bin.install "xero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.0/xero-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "73c8644d04a1f9f971af13bc3f4b10e162b643707285f90e1f9a319e21a99a3d"

      define_method(:install) do
        bin.install "xero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.0/xero-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "5c7f05f38ea4c2ff08e8c4d947a949d40ed16693759e33d141e7a27290ca6a53"
      define_method(:install) do
        bin.install "xero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.0/xero-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "e532d914734ee2593a5d5e7cbd66311b103057801e124e27f5656a150d316e7c"
      define_method(:install) do
        bin.install "xero"
      end
    end
  end

  test do
    assert_match "Xero", shell_output("#{bin}/xero --help")
  end
end
