# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XeroCli < Formula
  desc "CLI for the Xero accounting API"
  homepage "https://github.com/paulmeller/xero-cli"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.2/xero-cli_0.2.2_darwin_amd64.tar.gz"
      sha256 "dae6f3789e37a003daa19fd4058e781aada41ecbf596d9b147db81278c8a92e1"

      define_method(:install) do
        bin.install "xero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.2/xero-cli_0.2.2_darwin_arm64.tar.gz"
      sha256 "a05d49564afe0740f043f171d7426ac11a899971bc0340ed7c4bf51afdc992bd"

      define_method(:install) do
        bin.install "xero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.2/xero-cli_0.2.2_linux_amd64.tar.gz"
      sha256 "7460442c41d01a663be09e4a1b7f3aed48c9bd91207a063b5770d384558e96a2"
      define_method(:install) do
        bin.install "xero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paulmeller/xero-cli/releases/download/v0.2.2/xero-cli_0.2.2_linux_arm64.tar.gz"
      sha256 "7f02509c570a324fbec53d52ba660aefb47e0718a34197d0caef2a8632285003"
      define_method(:install) do
        bin.install "xero"
      end
    end
  end

  test do
    assert_match "Xero", shell_output("#{bin}/xero --help")
  end
end
